// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: bookmarked_businesses.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookmarkedBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BusinessId string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
}

func (x *CreateBookmarkedBusRequest) Reset() {
	*x = CreateBookmarkedBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookmarkedBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkedBusRequest) ProtoMessage() {}

func (x *CreateBookmarkedBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkedBusRequest.ProtoReflect.Descriptor instead.
func (*CreateBookmarkedBusRequest) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookmarkedBusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookmarkedBusRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type CreateBookmarkedBusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBookmarkedBusResponse) Reset() {
	*x = CreateBookmarkedBusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookmarkedBusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkedBusResponse) ProtoMessage() {}

func (x *CreateBookmarkedBusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkedBusResponse.ProtoReflect.Descriptor instead.
func (*CreateBookmarkedBusResponse) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{1}
}

type DeleteBookmarkedBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBookmarkedBusRequest) Reset() {
	*x = DeleteBookmarkedBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkedBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkedBusRequest) ProtoMessage() {}

func (x *DeleteBookmarkedBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkedBusRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkedBusRequest) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBookmarkedBusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteBookmarkedBusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBookmarkedBusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBookmarkedBusResponse) Reset() {
	*x = DeleteBookmarkedBusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkedBusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkedBusResponse) ProtoMessage() {}

func (x *DeleteBookmarkedBusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkedBusResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkedBusResponse) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{3}
}

type GetBookmarkedBusByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBookmarkedBusByIdRequest) Reset() {
	*x = GetBookmarkedBusByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookmarkedBusByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedBusByIdRequest) ProtoMessage() {}

func (x *GetBookmarkedBusByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedBusByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBookmarkedBusByIdRequest) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookmarkedBusByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBookmarkedBusByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBookmarkedBusByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BusinessId string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	Id         string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBookmarkedBusByIdResponse) Reset() {
	*x = GetBookmarkedBusByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookmarkedBusByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedBusByIdResponse) ProtoMessage() {}

func (x *GetBookmarkedBusByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedBusByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBookmarkedBusByIdResponse) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookmarkedBusByIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBookmarkedBusByIdResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *GetBookmarkedBusByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllBookmarkedBusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetAllBookmarkedBusRequest) Reset() {
	*x = GetAllBookmarkedBusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookmarkedBusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookmarkedBusRequest) ProtoMessage() {}

func (x *GetAllBookmarkedBusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookmarkedBusRequest.ProtoReflect.Descriptor instead.
func (*GetAllBookmarkedBusRequest) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllBookmarkedBusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllBookmarkedBusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Businesses []*GetBookmarkedBusByIdResponse `protobuf:"bytes,1,rep,name=businesses,proto3" json:"businesses,omitempty"`
}

func (x *GetAllBookmarkedBusResponse) Reset() {
	*x = GetAllBookmarkedBusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmarked_businesses_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookmarkedBusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookmarkedBusResponse) ProtoMessage() {}

func (x *GetAllBookmarkedBusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmarked_businesses_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookmarkedBusResponse.ProtoReflect.Descriptor instead.
func (*GetAllBookmarkedBusResponse) Descriptor() ([]byte, []int) {
	return file_bookmarked_businesses_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllBookmarkedBusResponse) GetBusinesses() []*GetBookmarkedBusByIdResponse {
	if x != nil {
		return x.Businesses
	}
	return nil
}

var File_bookmarked_businesses_proto protoreflect.FileDescriptor

var file_bookmarked_businesses_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62,
	0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x49, 0x64, 0x22, 0x1d, 0x0a, 0x1b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64,
	0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x1a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x46, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x64, 0x42, 0x75, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x1c, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0a, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x32, 0xb2,
	0x04, 0x0a, 0x15, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x83, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x31, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x83,
	0x01, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x31, 0x2e, 0x62, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x86, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x32, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x83, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x64, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x31, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x5f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bookmarked_businesses_proto_rawDescOnce sync.Once
	file_bookmarked_businesses_proto_rawDescData = file_bookmarked_businesses_proto_rawDesc
)

func file_bookmarked_businesses_proto_rawDescGZIP() []byte {
	file_bookmarked_businesses_proto_rawDescOnce.Do(func() {
		file_bookmarked_businesses_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookmarked_businesses_proto_rawDescData)
	})
	return file_bookmarked_businesses_proto_rawDescData
}

var file_bookmarked_businesses_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bookmarked_businesses_proto_goTypes = []any{
	(*CreateBookmarkedBusRequest)(nil),   // 0: bookmarked_businesses.CreateBookmarkedBusRequest
	(*CreateBookmarkedBusResponse)(nil),  // 1: bookmarked_businesses.CreateBookmarkedBusResponse
	(*DeleteBookmarkedBusRequest)(nil),   // 2: bookmarked_businesses.DeleteBookmarkedBusRequest
	(*DeleteBookmarkedBusResponse)(nil),  // 3: bookmarked_businesses.DeleteBookmarkedBusResponse
	(*GetBookmarkedBusByIdRequest)(nil),  // 4: bookmarked_businesses.GetBookmarkedBusByIdRequest
	(*GetBookmarkedBusByIdResponse)(nil), // 5: bookmarked_businesses.GetBookmarkedBusByIdResponse
	(*GetAllBookmarkedBusRequest)(nil),   // 6: bookmarked_businesses.GetAllBookmarkedBusRequest
	(*GetAllBookmarkedBusResponse)(nil),  // 7: bookmarked_businesses.GetAllBookmarkedBusResponse
}
var file_bookmarked_businesses_proto_depIdxs = []int32{
	5, // 0: bookmarked_businesses.GetAllBookmarkedBusResponse.businesses:type_name -> bookmarked_businesses.GetBookmarkedBusByIdResponse
	0, // 1: bookmarked_businesses.Bookmarked_Businesses.CreateBookmarkedBusiness:input_type -> bookmarked_businesses.CreateBookmarkedBusRequest
	2, // 2: bookmarked_businesses.Bookmarked_Businesses.DeleteBookmarkedBusiness:input_type -> bookmarked_businesses.DeleteBookmarkedBusRequest
	4, // 3: bookmarked_businesses.Bookmarked_Businesses.GetBookmarkedBusinessById:input_type -> bookmarked_businesses.GetBookmarkedBusByIdRequest
	6, // 4: bookmarked_businesses.Bookmarked_Businesses.GetAllBookmarkedBusiness:input_type -> bookmarked_businesses.GetAllBookmarkedBusRequest
	1, // 5: bookmarked_businesses.Bookmarked_Businesses.CreateBookmarkedBusiness:output_type -> bookmarked_businesses.CreateBookmarkedBusResponse
	3, // 6: bookmarked_businesses.Bookmarked_Businesses.DeleteBookmarkedBusiness:output_type -> bookmarked_businesses.DeleteBookmarkedBusResponse
	5, // 7: bookmarked_businesses.Bookmarked_Businesses.GetBookmarkedBusinessById:output_type -> bookmarked_businesses.GetBookmarkedBusByIdResponse
	7, // 8: bookmarked_businesses.Bookmarked_Businesses.GetAllBookmarkedBusiness:output_type -> bookmarked_businesses.GetAllBookmarkedBusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bookmarked_businesses_proto_init() }
func file_bookmarked_businesses_proto_init() {
	if File_bookmarked_businesses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookmarked_businesses_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBookmarkedBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBookmarkedBusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBookmarkedBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBookmarkedBusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetBookmarkedBusByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetBookmarkedBusByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllBookmarkedBusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmarked_businesses_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllBookmarkedBusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookmarked_businesses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookmarked_businesses_proto_goTypes,
		DependencyIndexes: file_bookmarked_businesses_proto_depIdxs,
		MessageInfos:      file_bookmarked_businesses_proto_msgTypes,
	}.Build()
	File_bookmarked_businesses_proto = out.File
	file_bookmarked_businesses_proto_rawDesc = nil
	file_bookmarked_businesses_proto_goTypes = nil
	file_bookmarked_businesses_proto_depIdxs = nil
}
